name: Deploy Blog

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Debug Node and NPM versions
        run: |
          node -v
          npm -v
          
      - name: Install dependencies
        run: |
          npm ci --prefer-offline
          
      - name: Build site
        run: |
          npm run build
          ls -la dist/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          full_commit_message: 'Deploy: ${{ github.sha }}'
          keep_files: true
